#!/bin/bash

set -e

d=$(date +%Y-%m-%d)
exdir=/media/michael/blue_wd/pictures/dslr/
sddir="/media/michael/NIKON D5300/DCIM/100D5300/"
locdir=/home/michael/photo/

# import jpgs
cd $exdir/JPGS/
mkdir ./$d-$1
cd ./$d-$1
echo "copying jpgs to" $(pwd)
cp -v "$sddir"/*.JPG ./
exiftool '-filename<CreateDate' -d %Y%m%d_%H%M%S%%-c.%%le -r -ext JPG ./

# import nef raw files
cd $exdir/RAW/
mkdir ./$d-$1
cd ./$d-$1
echo "copying nefs to" $(pwd)
cp -v "$sddir"/*.NEF ./
exiftool '-filename<CreateDate' -d %Y%m%d_%H%M%S%%-c.%%le -r -ext NEF ./

# import movies
echo "checking for movies"
count=`ls -1 "$sddir"/*.MOV 2>/dev/null | wc -l`
echo $count "movies found"
if [ "$count" != 0 ]
then
    cd $exdir
    cd ../../videos
    mkdir ./$d-$1
    cd ./$d-$1
    echo "copying movies to" $(pwd)
    cp -v "$sddir"/*.MOV ./
fi

# sync external drive with raw folder on computer

# echo "syncing external raw files to local files at" $locdir/RAW/
# rsync -a --info=progress2 $exdir/RAW/ $locdir/RAW/
