#!/bin/bash

set -e

recdir=/home/michael/Documents/website2/content/recipes/
index_ignore='images|*.css|index.html|template.html'

# sync recipes from category folders to all folder
cd $recdir
rsync -a --exclude 'index.html' \
    baking/ \
    beef/ \
    poultry/ \
    pork/ \
    seafood/ \
    sides_sauces_misc/ \
    vegetables/ \
    all/

# create index.html dir in each folder
tree baking/ -HD '.' -L 1 --noreport --charset utf-8 \
    -I "$index_ignore" --timefmt '%Y-%m-%d' > baking/index.html
tree beef/ -HD '.' -L 1 --noreport --charset utf-8 \
    -I "$index_ignore" --timefmt '%Y-%m-%d' > beef/index.html
tree poultry/ -HD '.' -L 1 --noreport --charset utf-8 \
    -I "$index_ignore" --timefmt '%Y-%m-%d' > poultry/index.html
tree pork/ -HD '.' -L 1 --noreport --charset utf-8 \
    -I "$index_ignore" --timefmt '%Y-%m-%d' > pork/index.html
tree seafood/ -HD '.' -L 1 --noreport --charset utf-8 \
    -I "$index_ignore" --timefmt '%Y-%m-%d' > seafood/index.html
tree sides_sauces_misc -HD '.' -L 1 --noreport --charset utf-8 \
    -I "$index_ignore" --timefmt '%Y-%m-%d' > sides_sauces_misc/index.html
tree vegetables/ -HD '.' -L 1 --noreport --charset utf-8 \
    -I "$index_ignore" --timefmt '%Y-%m-%d' > vegetables/index.html
tree all/ -HD '.' -L 1 --noreport --charset utf-8 \
    -I "$index_ignore" --timefmt '%Y-%m-%d' > all/index.html
tree products/ -HD '.' -L 1 --noreport --charset utf-8 \
    -I "$index_ignore" --timefmt '%Y-%m-%d' > products/index.html
tree -HD '.' -L 1 --noreport --charset utf-8 \
    -I "$index_ignore" --timefmt '%Y-%m-%d' > index.html

